// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBADMm-9T6c7vnhC60ir_e60Ph8WdOxdm8',
    appId: '1:152568960392:web:def069b65e700ae0a9d63d',
    messagingSenderId: '152568960392',
    projectId: 'coolapp-2c678',
    authDomain: 'coolapp-2c678.firebaseapp.com',
    storageBucket: 'coolapp-2c678.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5EpsIhARS_B-lOcyuEQd5HRSqPOJZQpE',
    appId: '1:152568960392:android:99063f20c6d8e3eba9d63d',
    messagingSenderId: '152568960392',
    projectId: 'coolapp-2c678',
    storageBucket: 'coolapp-2c678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuMCjAKPtnjT4JvxSJPMAxBrMINFMSXAE',
    appId: '1:152568960392:ios:35cc2f263624b7dba9d63d',
    messagingSenderId: '152568960392',
    projectId: 'coolapp-2c678',
    storageBucket: 'coolapp-2c678.appspot.com',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuMCjAKPtnjT4JvxSJPMAxBrMINFMSXAE',
    appId: '1:152568960392:ios:52a5d9bc5f2478c4a9d63d',
    messagingSenderId: '152568960392',
    projectId: 'coolapp-2c678',
    storageBucket: 'coolapp-2c678.appspot.com',
    iosBundleId: 'com.example.coolapp.RunnerTests',
  );
}
